#!/bin/bash

# usar "sudo gnome-terminal" para utizar terminal de root
directory=$(pwd)

# Descomapactar kernel no mesmo diretorio em /usr/src

tar -xvf kernel/linux-4.17.17.tar.xz -C /usr/src/

# indo para kernel descompactado
cd /usr/src/

# linkando pasta para diminuir trabalho com proximos comandos
ln -s linux-4.17.17 linux

cd linux

# inicio das configurações do kernel
echo "localmodconfig executando"
make localmodconfig | tee ${directory}/logsConfig/localmodconfigOUT.txt

# nano to enter kernel name
nano /usr/src/linux/Makefile

# making image
echo "bzImage executando"
echo "Time bzImage:" > ${directory}/logsConfig/times.txt

{ time  make bzImage > ${directory}/logsConfig/bzImageOUT.txt ; } 2> ${directory}/logsConfig/times.txt

# make modules
echo "modules executando"
echo "Time modules:" >> ${directory}/logsConfig/times.txt

{ time  make modules > ${directory}/logsConfig/modulesOUT.txt ; } 2>> ${directory}/logsConfig/times.txt

# make modules_install
echo "modules_install executando"
echo "Time modules_install:" >> ${directory}/logsConfig/times.txt

{ time  make modules_install > ${directory}/logsConfig/modules_installOUT.txt ; } 2>> ${directory}/logsConfig/times.txt

# make install
echo "install executando"
echo "Time install:" >> ${directory}/logsConfig/times.txt

{ time make install > ${directory}/logsConfig/installOUT.txt ; } 2>> ${directory}/logsConfig/times.txt

# kernel copilado



