#!/bin/bash

processNumber=$1

rm -r logsConfig
mkdir logsConfig
touch logsConfig/times.txt
directory=$(pwd)

# usar "sudo gnome-terminal" para utizar terminal de root

# Descomapactar kernel no mesmo diretorio em /usr/src

tar -xvf kernel/linux-4.17.17.tar.xz -C /usr/src/

# indo para kernel descompactado
cd /usr/src/

# linkando pasta para diminuir trabalho com proximos comandos
ln -s linux-4.17.17 linux

cd linux

# va em load e coloque o path para o .config desejado e salvar como .config

make menuconfig

nano /usr/src/linux/Makefile

initTime=`date +%s`
# making image
echo "bzImage executando"
echo "Time bzImage:" >> ${directory}/logsConfig/times.txt

{ time  make -j ${processNumber} bzImage > ${directory}/logsConfig/bzImageOUT.txt ; } 2>> ${directory}/logsConfig/times.txt 

# make modules
echo "modules executando"
echo "Time modules:" >> ${directory}/logsConfig/times.txt

{ time  make -j ${processNumber}  modules > ${directory}/logsConfig/modulesOUT.txt ; } 2>> ${directory}/logsConfig/times.txt

# make modules_install
echo "modules_install executando"
echo "Time modules_install:" >> ${directory}/logsConfig/times.txt

{ time  make modules_install > ${directory}/logsConfig/modules_installOUT.txt ; } 2>> ${directory}/logsConfig/times.txt

# make install
echo "install executando"
echo "Time install:" >> ${directory}/logsConfig/times.txt

{ time make install > ${directory}/logsConfig/installOUT.txt ; } 2>> ${directory}/logsConfig/times.txt

# kernel copilado
endTime=`date +%s`
grep 'Time\|real' ${directory}/logsConfig/times.txt > ${directory}/logsConfig/timeFormatted.txt

runtime=$((endTime - initTime))
echo "Final time: ${runtime}s" >> ${directory}/logsConfig/timeFormatted.txt

rm ${directory}/logsConfig/times.txt
